/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sergio
 */
public class CivitasView extends javax.swing.JFrame {

    /**
     * Creates new form CivitasView
     */
    
    private CivitasJuego juego;
    private JugadorPanel jugadorPanel;
    private GestionarDialog gestionarD;
    
    public CivitasView() {
        initComponents();
        jugadorPanel = new JugadorPanel();
        gestionarD = new GestionarDialog(this);
        contenedorVistaJugador.add(jugadorPanel);
        repaint();
        revalidate();
    }
    
    void mostrarSiguienteOperacion(OperacionesJuego operacion){
        siguienteOperacionT.setText(operacion.name());
        actualizarVista();
    }
    
    public void actualizarVista(){
        rankingL.setVisible(false);
        rankingT.setVisible(false);
        jugadorPanel.setJugador(juego.getJugadorActual());
        casillaT.setText(juego.getCasillaActual().toString());
        
        if (juego.finalDelJuego()){
            rankingL.setVisible(true);
            rankingT.setVisible(true);   
            rankingT.setText(juego.rankingS().toString());
        }
        
        repaint();
        revalidate();
    }
    
    public void setCivitasJuego(CivitasJuego j){
        juego = j;
        setVisible(true);
    }
    
    void mostrarEventos()
    {
        DiarioDialog diarioD = new DiarioDialog(this);
    }
    
    Respuestas comprar()
    {
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?","Compra",JOptionPane.YES_NO_OPTION);
        Respuestas salida = Respuestas.SI;
        if (opcion == 1)
            salida = Respuestas.NO;
        
        return salida;
    }
    
    int getGestion()
    {
        return gestionarD.getGestionElegida();
    }
    
    int getPropiedad()
    {
        return gestionarD.getPropiedadElegida();
    }
    
    void gestionar()
    {
        gestionarD.pack();
        gestionarD.gestionar(juego.getJugadorActual());
        gestionarD.revalidate();
    }
    
    SalidasCarcel salirCarcel()
    {
        String[] opciones = {"Pagando","Tirando"};
        
        int respuesta = JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la cárcel?",
                "Salir de la cárcel", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, opciones, opciones[0]);
        
        SalidasCarcel salida = SalidasCarcel.PAGANDO;
        if (respuesta == 1)
            salida = SalidasCarcel.TIRANDO;
        return salida;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloL = new javax.swing.JLabel();
        contenedorVistaJugador = new javax.swing.JPanel();
        casillaT = new javax.swing.JTextField();
        siguienteOperacionL = new javax.swing.JLabel();
        siguienteOperacionT = new javax.swing.JTextField();
        rankingL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rankingT = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloL.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        tituloL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloL.setText("CIVITAS");
        tituloL.setEnabled(false);

        casillaT.setEnabled(false);
        casillaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casillaTActionPerformed(evt);
            }
        });

        siguienteOperacionL.setText("Siguiente operación: ");
        siguienteOperacionL.setEnabled(false);

        siguienteOperacionT.setEnabled(false);

        rankingL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rankingL.setText("RÁNKING");
        rankingL.setEnabled(false);

        rankingT.setColumns(20);
        rankingT.setRows(5);
        rankingT.setEnabled(false);
        jScrollPane1.setViewportView(rankingT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(siguienteOperacionL)
                        .addGap(41, 41, 41)
                        .addComponent(siguienteOperacionT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(casillaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rankingL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(tituloL)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloL)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguienteOperacionL)
                    .addComponent(siguienteOperacionT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casillaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addComponent(rankingL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casillaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casillaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casillaTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField casillaT;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rankingL;
    private javax.swing.JTextArea rankingT;
    private javax.swing.JLabel siguienteOperacionL;
    private javax.swing.JTextField siguienteOperacionT;
    private javax.swing.JLabel tituloL;
    // End of variables declaration//GEN-END:variables
}
