/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Jugador;
import civitas.JugadorEspeculador;

/**
 *
 * @author sergio
 */
public class JugadorPanel extends javax.swing.JPanel {

    private Jugador jugador;
    
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }
    
    public void setJugador(Jugador jugador){
        
        this.jugador = jugador;
        nombreT.setText(jugador.getNombre());
        saldoT.setText(Float.toString(jugador.getSaldo()));
        encarceladoT.setText(Boolean.toString(jugador.isEncarcelado()));        
        especuladorT.setText(Boolean.toString(jugador.getClass() == JugadorEspeculador.class));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreT = new javax.swing.JTextField();
        saldoT = new javax.swing.JTextField();
        encarceladoT = new javax.swing.JTextField();
        especuladorT = new javax.swing.JTextField();
        nombreL = new javax.swing.JLabel();
        saldoL = new javax.swing.JLabel();
        encarceladoL = new javax.swing.JLabel();
        especuladorL = new javax.swing.JLabel();

        setEnabled(false);

        nombreT.setText("jTextField1");
        nombreT.setEnabled(false);
        nombreT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTActionPerformed(evt);
            }
        });

        saldoT.setText("jTextField2");
        saldoT.setEnabled(false);

        encarceladoT.setText("jTextField3");
        encarceladoT.setEnabled(false);

        especuladorT.setText("jTextField4");
        especuladorT.setEnabled(false);

        nombreL.setText("Nombre:");

        saldoL.setText("Saldo:");

        encarceladoL.setText("Encarcelado:");

        especuladorL.setText("Especulador:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreL)
                    .addComponent(saldoL)
                    .addComponent(encarceladoL)
                    .addComponent(especuladorL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encarceladoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especuladorT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreL))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldoL))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encarceladoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encarceladoL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especuladorT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especuladorL))
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel encarceladoL;
    private javax.swing.JTextField encarceladoT;
    private javax.swing.JLabel especuladorL;
    private javax.swing.JTextField especuladorT;
    private javax.swing.JLabel nombreL;
    private javax.swing.JTextField nombreT;
    private javax.swing.JLabel saldoL;
    private javax.swing.JTextField saldoT;
    // End of variables declaration//GEN-END:variables
}
